apiVersion: v1
kind: Pod
metadata:
  name: building-app
  labels:
    app: webapp
spec:
  containers:
  - name: webapp-floyed
    imagePullPolicy: IfNotPresent
    image: floyedpinto08/webapp-k8s:0.1
  imagePullSecrets:
  - name: regcred